added classification of new data
giorgiosavastano/cassa pull request #16
Opened 2022-05-02 10:08 UTC by giorgiosavastano

Hey Karl,

I added a couple of methods for the classification of new data. Let me know if you have any comments.

Ciao,
Giorgio

2022-05-02 16:42 UTC, karl-nordstrom requested changes

2022-05-02 16:42 UTC, karl-nordstrom commented on src/cassa/distance_matrix.py
> +    def classify_new_data(self, new_data, top=10):
Could you maybe add some sphinx doc strings to all of the functions in this package? It's getting a bit more complicated now and having clear documentation of inputs and outputs every function takes would be very handy!

2022-05-02 16:42 UTC, karl-nordstrom commented on src/cassa/distance_matrix.py
> +                int(np.arange(len(dist_arr))[dist_arr == d])
This is a slightly strange way to select the smallest distances indices. I would use https://numpy.org/doc/stable/reference/generated/numpy.argsort.html on the distance array instead.

2022-05-02 16:42 UTC, karl-nordstrom commented on src/cassa/distance_matrix.py
> +        assert np.argmin(dist_arr) == inds_arr[0]
This assert is a bit confusing -- capture this with a test instead.

2022-05-02 16:42 UTC, karl-nordstrom commented on tests/test_classification_pipeline.py
> +    def test_classify_new_data(self):
Not related directly to this function but the overall test coverage is below 80%, it would maybe make sense to take a look at which parts of the code are not covered and implement some extra tests for them? I don't think 100% necessarily makes sense to target but less than 80% is quite low.

2022-05-03 06:36 UTC, giorgiosavastano commented on src/cassa/distance_matrix.py
> +    def classify_new_data(self, new_data, top=10):
Good point, will do!

2022-05-03 06:36 UTC, giorgiosavastano commented on src/cassa/distance_matrix.py
> +                int(np.arange(len(dist_arr))[dist_arr == d])
For some reason I didn't realized that was a function that does this! Thanks

2022-05-03 13:50 UTC, giorgiosavastano commented on tests/test_classification_pipeline.py
> +    def test_classify_new_data(self):
I am actually not sure why coverage doesn't detect that `_emd_proc` and `_emd_proc_new_data` are tested. Do you have any ideas why?

2022-05-09 21:37 UTC, karl-nordstrom approved these changes
LGTM

2022-05-09 21:37 UTC, karl-nordstrom commented on tests/test_classification_pipeline.py
> +    def test_classify_new_data(self):
I think it's because coverage doesn't work with multiprocessing without some extra work. You could write unit tests which test those functions in isolation (which would be a good idea in general!).

2022-05-10 06:09 UTC, merged